baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'erduoya'
theme = 'PaperMod'

[params]
  env = "production"
  defaultTheme = "auto"
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true
  customCSS = ["/css/custom.css"]

[params.homeInfoParams]
  Title = "个人记录分享"
  Content = "这里是我的个人博客，记录生活、技术和思考"

[params.profileMode]
  enabled = false

# 背景图配置
[params.cover]
  linkFullImages = true
  image = "images/background.jpg"
  relative = false
  hidden = false
  responsiveImages = true

[params.assets]
  favicon = ""
  favicon16x16 = ""
  favicon32x32 = ""
  apple_touch_icon = ""
  safari_pinned_tab = ""

[[menu.main]]
  identifier = "时间轴"
  name = "时间轴"
  url = "/archives"
  weight = 10
  [menu.main.params]
    icon = "fa-solid fa-clock"

[[menu.main]]
  identifier = "碎碎念"
  name = "碎碎念"
  url = "/memos/"
  weight = 20
  [menu.main.params]
    icon = "fa-solid fa-pen"

[[menu.main]]
  identifier = "书签"
  name = "书签"
  url = "/collect/"
  weight = 30
  [menu.main.params]
    icon = "fa-solid fa-bookmark"

[[menu.main]]
  identifier = "图片墙"
  name = "图片墙"
  url = "/gallery/"
  weight = 40
  [menu.main.params]
    icon = "fa-solid fa-images"

[[menu.main]]
  identifier = "友联"
  name = "友联"
  url = "/friends/"
  weight = 50
  [menu.main.params]
    icon = "fa-solid fa-link"

[[menu.main]]
  identifier = "关于"
  name = "关于"
  url = "/about/"
  weight = 60
  [menu.main.params]
    icon = "fa-solid fa-user"

[[menu.main]]
  identifier = "工具"
  name = "工具"
  url = "#"
  weight = 70
  [menu.main.params]
    icon = "fa-solid fa-toolbox"

[[menu.main]]
  name = "云盘"
  url = "https://pan.erduoya.top/d/a00f8f0a429a4114bede/"
  parent = "工具"
  weight = 1
  [menu.main.params]
    icon = "fa-solid fa-hard-drive"

[[menu.main]]
  name = "监控"
  url = "https://stats.uptimerobot.com/8x97TZ6H3G"
  parent = "工具"
  weight = 2
  [menu.main.params]
    icon = "fa-solid fa-compass"

[[menu.main]]
  name = "图床"
  url = "https://imgse.com/"
  parent = "工具"
  weight = 3
  [menu.main.params]
    icon = "fa-solid fa-image"

